version: "3.7"

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: fe_nginx
    ports:
      - "80:80"
    volumes:
      - ./site:/site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    container_name: fe_php
    volumes:
      - ./site:/site
